/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Varun' at '14/11/18 10:49 AM' with Gradle 3.0
 *
 * @author Varun, @date 14/11/18 10:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
